### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by Tobias-08** [mauroservienti/NServiceBus.IntegrationTesting#172]
Hi @mauroservienti,
 
promising library, enabling completely new testing opportunities with NServiceBus!

Regarding dependency injection:

Is it possible to use generic host's dependency injection mechanisms (`ConfigureServices()`) in combination with `NServiceBus.IntegrationTesting`? I assume possibly not because `NServiceBus.AcceptanceTesting` might not (yet? Version 8?) use generic host?

Context:

Our endpoints use generic host and inject a `Microsoft.Extensions.Logging.ILogger` instance in the handlers (via Serilog's `UseSerilog()`). When using `NServiceBus.IntegrationTesting` I get a `System.InvalidOperationException: Unresolved dependency` during handler execution. Attempts to register Serilog via `endpointConfiguration.RegisterComponent` didn't work either (but maybe I did something wrong).

Do you have a sample for DI with `NServiceBus.IntegrationTesting` (also mocks would be fine, we don't need a working Serilog during integration testing)?

Thanks!
Tobias

**Comment by mauroservienti** [comment]
Thanks for raising this issue @Tobias-08 

> Is it possible to use generic host's dependency injection mechanisms (`ConfigureServices()`) in combination with `NServiceBus.IntegrationTesting`? I assume possibly not because `NServiceBus.AcceptanceTesting` might not (yet? Version 8?) use generic host?

I don't know. It's worth investigating. I'll have a look at a possible configuration using the generic host in the next few days.

**Comment by mauroservienti** [comment]
@Tobias-08 I spent some time investigating available options. It's not simple, but my gut feeling tells me that the generic host scenario can be supported.

I'll try to find the time to raise a spike PR during the weekend, if little Dracula 🧛‍♂️ agrees 😆 otherwise next week.

**Comment by mauroservienti** [comment]
I started outlining what’s needed in https://github.com/mauroservienti/NServiceBus.IntegrationTesting/issues/174

**Comment by Tobias-08** [comment]
@mauroservienti Sounds good, thanks for investigating.

**Comment by mauroservienti** [comment]
@Tobias-08 #179 is green. I never used Serilog, would you mind sharing a sample config with the generic host so that I can add it to the PR and verify that it works as expected?

**Comment by mauroservienti** [comment]
@Tobias-08 I went ahead and read some documentation about Serilog, I added the following https://github.com/mauroservienti/NServiceBus.IntegrationTesting/pull/177/commits/b2f12362b0bf1d911eba6e6c278c6a4f46a0d4c5 to one of the endpoints in the tests. Could you please verify that it's the correct Serilog setup that mimics your scenario?

**Comment by Tobias-08** [comment]
@mauroservienti I was off since Friday afternoon. I'll have a look now.

**Comment by Tobias-08** [comment]
@mauroservienti Looks good to me, only some minor comments.

**Comment by mauroservienti** [comment]
Thanks for the review @Tobias-08. I'll get it from there and release 1.1 soon.

**Comment by mauroservienti** [comment]
@Tobias-08 [NServiceBus.IntegrationTesting 1.1.0](https://www.nuget.org/packages/NServiceBus.IntegrationTesting/1.1.0) is available on Nuget. Thanks for raising this issue and for the PR review.

**Comment by Tobias-08** [comment]
@mauroservienti Thanks for extending your library so quickly. I'll give it a try this week.
