### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by Tobias-08** [mauroservienti/NServiceBus.IntegrationTesting#175]
@mauroservienti Do you accept contributions/PRs? I have some slight adjustments to the docs.

**Comment by mauroservienti** [comment]
Absolutely! That would be greatly appreciated 😄

**Comment by Tobias-08** [comment]
:-) While trying to push my branch I'm getting a 403 at the moment. Do you have to explicitly grant permissions or am I doing something wrong on my side (I'm not yet experienced in github-contributions)?

**Comment by Tobias-08** [comment]
What I missed was that I had to go via a fork. Learned something new...
